"""Write src/imgs.ts: the pixel size of every image in public/img (scenes need real sizes to place images)."""
import glob, os
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__)); PUB = os.path.join(HERE, "..", "public")
rows = []
for f in sorted(glob.glob(os.path.join(PUB, "img", "**", "*.*"), recursive=True)):
    if f.lower().endswith((".jpg", ".jpeg", ".png")) and "/masks/" not in f:
        w, h = Image.open(f).size
        rows.append(f"  '{os.path.relpath(f, PUB)}': [{w}, {h}],")
open(os.path.join(HERE, "..", "src", "imgs.ts"), "w").write(
    "// Generated by tools/img_sizes.py: pixel size of every image in public/img. Re-run after adding images.\n"
    "export const IMG: Record<string, [number, number]> = {\n" + "\n".join(rows) + "\n};\n")
print(len(rows), "images")
